### ISSUE TITLE
Problema no desafio 10 - Rodapé

### ISSUE THREAD

**Issue by Denilsonalbertomarques** [gustavoguanabara/html-css#551]
Quando rodo meu site em telas pequenas, o rodapé não ocupa a largura inteira da tela

**Comment by BenjamimCS** [comment]
Descreva melhor por favor. Explique com código e imagens.

**Comment by Denilsonalbertomarques** [comment]
TODOS OS CÓDIGOS QUE UTILIZEI NO RODAPÉ:

footer {
    background-color: var(--cor04);
}

footer p {
    font-size: 0.9em;
    color: white;
    text-align: center;
}

footer a {
    text-decoration: none;
    color: white;
}

footer a:hover {
    text-decoration: underline;
    font-family: var(--fonte-paragrafo);
}

**Comment by Denilsonalbertomarques** [comment]
![Uploading Screenshot_20240206-143934.png…]()

**Comment by Denilsonalbertomarques** [comment]
![Screenshot_20240206-143934](https://github.com/gustavoguanabara/html-css/assets/158228987/1cfae0d2-a908-444d-ad42-72b545e74abc)

**Comment by EdsonRafaelS** [comment]
Possivelmente, seu footer deve esta com width diferente de 100%

`footer{
           width= 100%;
}`

**Comment by BenjamimCS** [comment]
DESCULPAS A DEMORA.

No Inspecionar do navegador vá na aba "Computado" e veja os valores das  propriedades de largura, principalmente a `width`: veja se não há valor absoluto como `px`, ou se esteja com alguma porcentagem etc.

**Comment by flameastro** [comment]
Olá, @Denilsonalbertomarques! Sobre esse problema do rodapé, você precisa configurar o rodapé com uma `largura` (`width`) de 100%. Aqui está o seu código corrigido:


``` css
footer {
    background-color: var(--cor04);
    width: 100%;
}

footer p {
    font-size: 0.9em;
    color: white;
    text-align: center;
}

footer a {
    text-decoration: none;
    color: white;
    transition: all 0.3s ease-in-out; /* Adicionei uma transição suave também */
}

footer a:hover {
    text-decoration: underline;
    font-family: var(--fonte-paragrafo);
}
```

Só uma coisa a reparar: Se você colocar width como 100vw, as vezes ele pode ocupar toda a tela (incluindo a rolagem lateral) e criar uma rolagem horizontal, o que é muito ruim. Então, sempre utilize 100% nessas situações! 🖖🏻

Espero ter ajudado! Feche a issue se resolveu o problema, por favor!
