### ISSUE TITLE
Desafio 11 modulo 2

### ISSUE THREAD

**Issue by JuanRodrigues-Dev** [gustavoguanabara/html-css#778]
Estou com roblema em sempre deixar a imagem 2 no centro

**Comment by BenjamimCS** [comment]
Tem um jeito de posicionar o astronauta no centro:
```CSS
img {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

Pra mais consulte as propriedades no [MDN](https://developer.mozilla.com).
